/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      colors: {
        'surface-app': 'var(--bg-app)',
        'surface-primary': 'var(--bg-primary)',
        'surface-secondary': 'var(--bg-secondary)',
        'surface-tertiary': 'var(--bg-tertiary)',
        'surface-muted': 'var(--bg-muted)',
        'surface-hover': 'var(--bg-hover)',
        'border-subtle': 'var(--border-subtle)',
        'border-strong': 'var(--border-strong)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-inverse': 'var(--text-inverse)',
        'accent-green': 'var(--accent-green)',
        'accent-green-strong': 'var(--accent-green-emphasis)',
        'accent-green-muted': 'var(--accent-green-muted)',
        'accent-green-border': 'var(--accent-green-border)',
        'accent-blue': 'var(--accent-blue)',
        'accent-blue-strong': 'var(--accent-blue-emphasis)',
        'accent-blue-muted': 'var(--accent-blue-muted)',
        'accent-blue-border': 'var(--accent-blue-border)',
        'accent-purple': 'var(--accent-purple)',
        'accent-purple-strong': 'var(--accent-purple-emphasis)',
        'accent-purple-muted': 'var(--accent-purple-muted)',
        'accent-purple-border': 'var(--accent-purple-border)',
        'accent-yellow': 'var(--accent-yellow)',
        'accent-yellow-strong': 'var(--accent-yellow-emphasis)',
        'accent-yellow-muted': 'var(--accent-yellow-muted)',
        'accent-yellow-border': 'var(--accent-yellow-border)',
        'accent-orange': 'var(--accent-orange)',
        'accent-orange-strong': 'var(--accent-orange-emphasis)',
        'accent-orange-muted': 'var(--accent-orange-muted)',
        'accent-orange-border': 'var(--accent-orange-border)',
        'accent-red': 'var(--accent-red)',
        'accent-red-strong': 'var(--accent-red-emphasis)',
        'accent-red-muted': 'var(--accent-red-muted)',
        'accent-red-border': 'var(--accent-red-border)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
    },
  },
  plugins: [],
  corePlugins: {
    fontVariantNumeric: true,
  },
}
